# Generated by Django 5.2 on 2025-05-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cca2', models.CharField(max_length=4, unique=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('timezones', models.JSONField()),
                ('languages', models.JSONField()),
                ('flag_png', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
